Add exercise notebooks
pytroll/pytroll-examples pull request #6
Opened 2018-10-04 09:32 UTC by mraspaud

2018-10-08 19:35 UTC, djhoese requested changes
Looks really good. There is a good balance of skipping over complex subjects and detailing the important ones. There are a few typos and things that don't sound quite right. Most of it looks good except for a few places where I think more details (ex 'coordinates') could be useful. This is a good starting point that could be followed up with sections on dynamically specifying datasets in the file handler and in the future filtering out what datasets are available.

2018-10-08 19:35 UTC, djhoese commented on pytroll-exercise-2018-10/5-custom-reader.ipynb
> +    "In order to add a reader to satpy, you will need to implement two files:\n",
"create" versus "implement"

2018-10-08 19:35 UTC, djhoese commented on pytroll-exercise-2018-10/5-custom-reader.ipynb
> +    "For this tutorial, we will implement a reade for the Eumetsat NetCDF format for SEVIRI data"
typo "reade"

2018-10-08 19:35 UTC, djhoese commented on pytroll-exercise-2018-10/5-custom-reader.ipynb
> +    "- the `reader` section, that gives a general parameters of the reader\n",
"that provides basic parameters for the reader"

2018-10-08 19:35 UTC, djhoese commented on pytroll-exercise-2018-10/5-custom-reader.ipynb
> +    "The `reader` section, that gives a general parameters of the reader.\n",
Same suggestion as above.

2018-10-08 19:35 UTC, djhoese commented on pytroll-exercise-2018-10/5-custom-reader.ipynb
> +    "        nc_seviri_l1b_hrv:\n",
At least on github's rendering of this code block the second file type `nc_seviri_l1b_hrv` is over-indented.

2018-10-08 19:35 UTC, djhoese commented on pytroll-exercise-2018-10/5-custom-reader.ipynb
> +    "The datasets section describes each dataset available in the files. The parameters provided are made available to the methods of the implementing class.\n",
"made available to the methods of the implementing class" didn't make sense to me at first, but I suppose this is good enough. Or maybe "These parameters are made available to the file handling python code." or something like that.

2018-10-08 19:35 UTC, djhoese commented on pytroll-exercise-2018-10/5-custom-reader.ipynb
> +    " - and any other field that is relevant for the reader\n",
Maybe add something about "standard_name" and "units" if they are not available from the file since these are pretty important in the rest of satpy.

2018-10-08 19:35 UTC, djhoese commented on pytroll-exercise-2018-10/5-custom-reader.ipynb
> +    "- the `__init__` method, that takes as arguments the filename, the filename info that we get by parsing the filename using the pattern defined in the yaml file, and the filetype info that we get
"the filename info that we get by parsing the filename using the pattern defined in the yaml file". Can you put "dictionary" in there somewhere?

2018-10-08 19:35 UTC, djhoese commented on pytroll-exercise-2018-10/5-custom-reader.ipynb
> +    "- the `__init__` method, that takes as arguments the filename, the filename info that we get by parsing the filename using the pattern defined in the yaml file, and the filetype info that we get
should be "receive"

2018-10-08 19:35 UTC, djhoese commented on pytroll-exercise-2018-10/5-custom-reader.ipynb
> +    "- the `get_dataset` method, which takes as arguments the dataset ID of the dataset to load and the dataset info that is the description of the channel in the YAML file. This method has to return
Is `None` a valid return value or does it have to raise an exception? I wouldn't mind exceptions being mentioned here.

2018-10-08 19:35 UTC, djhoese commented on pytroll-exercise-2018-10/5-custom-reader.ipynb
> +    "- the `get_area_def` method, that takes as single argument the dataset ID for which we want the area. For the data that does cannot be geolocated with an area definition, the pixel coordinates n
This method is optional and glosses over the importance of `coordinates`. Is there an easy way to say "If the data cannot be geolocated with an area definition then the `dataset` section should specify `coordinates: [longitude_dataset, latitude_dataset]`. Also typo in "For the data that does cannot be".

2018-10-08 19:35 UTC, djhoese commented on pytroll-exercise-2018-10/5-custom-reader.ipynb
> +    "On top of that, two attributes need to be defined: `start_time` and `end_time`, that define the start and end times of the sensing."
I know you said the code wasn't ready but adding the start/end time properties would make this clear. Also the previous sentence doesn't say what type is returned by `get_bounding_box`.

2018-10-08 19:39 UTC, mraspaud commented
thanks a lot for the thorough review ! I will fix the notebook accordingly. My objective is to show the possibilities, while trying to keep things simple not to scare off potential contributors.

2019-01-29 19:27 UTC, djhoese commented
@mraspaud I forgot about this PR. Should this be merged?

2019-01-29 19:27 UTC, djhoese approved these changes

2019-02-03 13:59 UTC, merged